join:
  admin:
    permission: "join.admin"
    message: "%player% &c&lDołączył na serwer"

database:
  type: MYSQL
  host: 'localhost'
  port: 3306
  user: 'root'
  password: ''
  database-name: 'eggcore'